FROM	debian:buster

RUN		apt-get update -y && \
		apt-get upgrade -y && \
		apt-get install nginx -y \
		php7.3 \
		php-fpm \
		php-cli \
		wget \
		curl \
		php-mysql \
		php-xml \
		sendmail \
		vim \

# COPY	./tools/* /tools/

# RUN		chmod 777 /tools/init.sh

