SET
	PASSWORD FOR '$MARIADB_ADMIN_USER'@'*' = PASSWORD('$MARIADB_ADMIN_PASSWORD');

CREATE DATABASE IF NOT EXISTS $MARIADB_DATABASE;

-- Create Another User for WordPress
CREATE USER '$MARIADB_USER'@'%' IDENTIFIED BY '$MARIADB_PASSWORD';

-- Grant Permissions
GRANT ALL PRIVILEGES ON $MARIADB_DATABASE.* TO '$MARIADB_USER'@'%' WITH GRANT OPTION;

-- Apply
FLUSH PRIVILEGES;
