version: '3'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    env_file:
        - .env
    ports:
      - "3308:3306"
    image: mariadb
    networks:
      - my_docker
    tty: true
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    extra_hosts:
      - "sichoi.42.fr:127.0.0.1"
    restart: always
    ports:
      - "443:443"
    volumes:
      - data:/var/www/html
    image: nginx
    networks:
      - my_docker
    tty: true
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env
    image: wordpress
    volumes:
      - data:/var/www/html
    expose:
      - "9000"
    networks:
      - my_docker
    tty: true

networks:
  my_docker:
    driver: bridge

volumes:
  data: {}
